# Will automatically find an available port
server.port=0

# OR use a specific port
server.port=8081

spring.data.mongodb.database=test
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017